In [8]:
import os
import pandas as pd
from bs4 import BeautifulSoup as bs

DataPath = os.path.join(os.getcwd(), 'data', 'html_job_postings')
df = pd.DataFrame()

for file in os.listdir(DataPath):
    FullPath = os.path.join(DataPath, file)
    
    with open(FullPath, 'r', encoding='UTF-8') as Data:
        paragraph_list = []
        bullets_list = []
        soup = bs(Data)
        title = soup.title.text.strip()
        paragraphs = soup.find_all('p')
        if soup.find_all('ul'):
            bullets = soup.find_all('ul')
        else:
            bullets = soup.find_all('li')


        for paragraph in paragraphs:
            paragraph_list.append(paragraph.text.strip())

                
        for bullet in bullets: 
            bullets_list.append(bullet.text.strip())

        joined_bullet_list = ','.join(bullets_list)
        joined_paragraph_list = ','.join(paragraph_list)
        dict_to_import = {'Title':title,'Body': joined_paragraph_list,'Bullets':joined_bullet_list,'Path':file}
        df = df.append(dict_to_import,ignore_index=True)

df2 = df[df['Title'].str.match(r'.*Data.*')]
#df2.to_csv(r'C:\Users\John\Desktop\python\liveProject_resume\resume-job-posting-nlp-project\csv.csv')

In [10]:
df2 = df[df['Title'].str.match(r'.*Data.*')]
df2.to_csv(r'C:\Users\John\Desktop\python\liveProject_resume\resume-job-posting-nlp-project\csv.csv')

In [21]:
df2['duplicate'] = df2.duplicated(subset='Bullets', keep=False)
df2.loc[df2['duplicate'] == True]

c:\users\john\desktop\python\liveproject_resume\resume-job-posting-nlp-project\venv\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

,Body,Bullets,Path,Title,duplicate
27,,Lead lectures and educational coding activitie...,06f4f89b2121d668_fccid.html,Data Analytics Instructor - University of Sout...,True
36,"Where good people build rewarding careers.,Thi...",Conduct state of the art research in Natural L...,08be917f002760ce_fccid.html,Data Scientist: Deep Learning & NLP - Menlo Pa...,True
44,,"Selecting features, building and optimizing cl...",0a518d7e56e7635e_fccid.html,"Data Scientist - Aliso Viejo, CA",True
50,"Senior Data Scientist, VSP Vision care,Nearest...",,0af867267ad42e1d_fccid.html,"Senior Data Scientist, VSP Vision care - Ranch...",True
59,,"Design, build, and deploy innovative models an...",0cfd12bcc3976b90_fccid.html,"Corporate Control Management - Data Scientist,...",True
...,...,...,...,...,...
1270,"Position Description,Minimum Qualifications,Ad...",Deliver insights & recommendations in support ...,f3da022757d22cfd_fccid.html,Data Scientist - Customer Analytics - San Brun...,True
1282,",","Languages: Python, PySpark, SQL\nData Tools: S...",f579e807b5804620_fccid.html,"Data Scientist - New York, NY",True
1289,"Position Description,Minimum Qualifications,Ad...",Ph. D. in computer science or similar field or...,f7073e5203088d8f_fccid.html,"Staff Data Scientist - NLP - Sunnyvale, CA 94087",True
1310,,Develop sufficient understanding of business o...,fa9a55a5da854e49_fccid.html,"Data Scientist - Green Bay, WI",True
1335,Innovate. Collaborate. Shine. Lighthouse – KPM...,"Lead workshops, innovation sessions with clien...",_p.html,"Director, Data Scientist, Natural Language Pro...",True

In [22]:
df2.drop_duplicates(subset='Bullets', keep='first', inplace=True)

c:\users\john\desktop\python\liveproject_resume\resume-job-posting-nlp-project\venv\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [34]:
df2.to_csv(r'C:\Users\John\Desktop\python\liveProject_resume\resume-job-posting-nlp-project\csv.csv')

In [32]:
df2 = df2.drop(columns='duplicate')

In [33]:
df2.describe

<bound method NDFrame.describe of                                                    Body  \
0     Celebrating its twenty-fifth anniversary in 20...
1     ,JOB DESCRIPTION: Data Analysts apply tools an...
2     Data Scientist,Newark, CA,Full-Time, Direct Hi...
6     PwC Labs is focused on standardizing, automati...
7     The Washington Health Benefit Exchange is a pu...
...                                                 ...
1321  Like to be part of building something new? Thi...
1328
1330  SSRS Data Scientist,SSRS, a leading data-drive...
1331
1334  ,Required Skills:,· Looking for a candidate to...

                                                Bullets  \
0     Bachelor’s or Master’s degree in statistics, o...
1     US Citizenship is required.\nDesignated or Ran...
2     Design, develop, document and maintain machine...
6     Invite and provide evidence-based feedback in ...
7     Design, develop, test, and deploy reports usin...
...                                                 ...
1321  Work as part of a team of data scientists to d...
1328  Apply statistics techniques to improve Wish’s ...
1330  Use machine learning methods (e.g., cluster an...
1331  Performing ad-hoc statistical analysis (linear...
1334  The primary job responsibility is to migrate e...

                             Path  \
0     001b92395ed0fb62_fccid.html
1     00321a48d04fe754_fccid.html
2     0079c11b2611349f_fccid.html
6     0179ea131f141400_fccid.html
7     018866568cd5a0b0_fccid.html
...                           ...
1321  fc9a3ea9358239cf_fccid.html
1328  fe2838f305466298_fccid.html
1330  fee42538d4a7bb9a_fccid.html
1331  fefb9642ac28b85e_fccid.html
1334                 sample1.html

                                                  Title
0                    Data Engineer - Columbus, GA 31909
1                          Data Analyst - St. Louis, MO
2                           Data Scientist - Newark, CA
6     PwC Labs - Jr. Data Scientist - Machine Learni...
7        Data and Reporting Analyst - Olympia, WA 98501
...                                                 ...
1321           Lead Data Scientist - Portland, OR 97239
1328           Data Scientist - San Francisco, CA 94103
1330                    Data Scientist - Glen Mills, PA
1331              Data Analyst (Part-Time) - Austin, TX
1334                    Data Engineer - Bridgewater, NJ

[607 rows x 4 columns]>