In [11]:
import os
import pandas as pd
from bs4 import BeautifulSoup as bs

DataPath = os.path.join(os.getcwd(), 'data', 'html_job_postings')
df = pd.DataFrame()

for file in os.listdir(DataPath):
    FullPath = os.path.join(DataPath, file)
    
    with open(FullPath, 'rb') as Data:
        paragraph_list = []
        bullets_list = []
        soup = bs(Data)
        title = soup.title.text.strip()
        paragraphs = soup.find_all('p')
        if soup.find_all('ul'):
            bullets = soup.find_all('ul')
        else:
            bullets = soup.find_all('li')


        for paragraph in paragraphs:
            paragraph_list.append(paragraph.text.strip())

                
        for bullet in bullets: 
            bullets_list.append(bullet.text.strip())

        joined_bullet_list = [''.join(bullets_list)]
        joined_paragraph_list = [''.join(paragraph_list)]
        dict_to_import = {'Title':title,'Body': joined_paragraph_list,'Bullets':joined_bullet_list,'Path':file}
        df = df.append(dict_to_import,ignore_index=True)

df2 = df[df['Title'].str.match(r'.*Data.*')]
df2.to_csv(r'C:\Users\John\Desktop\python\liveProject_resume\resume-job-posting-nlp-project\csv.csv')

Empty DataFrame
Columns: [Body, Bullets, Path, Title]
Index: []

,Body,Bullets,Path,Title
0,[Celebrating its twenty-fifth anniversary in 2...,"[Bachelor’s or Master’s degree in statistics, ...",001b92395ed0fb62_fccid.html,"Data Engineer - Columbus, GA 31909"
1,[JOB DESCRIPTION: Data Analysts apply tools an...,[US Citizenship is required.\nDesignated or Ra...,00321a48d04fe754_fccid.html,"Data Analyst - St. Louis, MO"
2,"[Data ScientistNewark, CAFull-Time, Direct Hir...","[Design, develop, document and maintain machin...",0079c11b2611349f_fccid.html,"Data Scientist - Newark, CA"
6,"[PwC Labs is focused on standardizing, automat...",[Invite and provide evidence-based feedback in...,0179ea131f141400_fccid.html,PwC Labs - Jr. Data Scientist - Machine Learni...
7,[The Washington Health Benefit Exchange is a p...,"[Design, develop, test, and deploy reports usi...",018866568cd5a0b0_fccid.html,"Data and Reporting Analyst - Olympia, WA 98501"
...,...,...,...,...
1328,[],[Apply statistics techniques to improve Wish’s...,fe2838f305466298_fccid.html,"Data Scientist - San Francisco, CA 94103"
1330,"[SSRS Data ScientistSSRS, a leading data-drive...","[Use machine learning methods (e.g., cluster a...",fee42538d4a7bb9a_fccid.html,"Data Scientist - Glen Mills, PA"
1331,[],[Performing ad-hoc statistical analysis (linea...,fefb9642ac28b85e_fccid.html,"Data Analyst (Part-Time) - Austin, TX"
1334,[Required Skills:· Looking for a candidate to ...,[The primary job responsibility is to migrate ...,sample1.html,"Data Engineer - Bridgewater, NJ"
1335,[Innovate. Collaborate. Shine. Lighthouse – KP...,"[Lead workshops, innovation sessions with clie...",_p.html,"Director, Data Scientist, Natural Language Pro..."